### ISSUE TITLE
OAuth2 library dependency suddenly removed as of 2.6.1

### ISSUE THREAD

**Issue by Luxusio** [googleapis/java-kms#847]
#### Environment details

1. Specify the API at the beginning of the title. For example, "BigQuery: ...").
   General, Core, and Other are also allowed as types
2. OS type and version: macOS Monterey 12.5.1 M1
3. Java version: 17
4.  version(s): 2.6.4

#### Steps to reproduce

  1. Use GoogleCredentials class in com.google.auth:google-auth-library-oauth2-http library
  2. Update library to 2.6.1+ (in my case, 2.6.4)

#### Code example

```kotlin
    private fun createCredential(): GoogleCredentials {
        val transport = NetHttpTransport()
        val credential = GoogleCredentials.fromStream(javaClass.getResourceAsStream(googleAuthKeyFileName)) { transport }

        return credential.createScoped(KeyManagementServiceSettings.getDefaultServiceScopes())
    }
```

#### Any additional information below

It just fails the build.  
  
there's no update log  
https://cloud.google.com/java/docs/reference/google-cloud-kms/latest/history  
  
I hope the com.google.auth:google-auth-library-oauth2-http dependency is added back.

**Comment by alicejli** [comment]
Hi! Thanks for flagging - it was indeed changed to a `runtime` dependency here: https://github.com/googleapis/java-kms/pull/835

Apologies the release notes didn't catch the change as it was a manual fix that was slipped in, so it wasn't explicitly stated. We'll be more cautious in the future about ensuring commit notes are thorough. 

We generally don't expose transitive dependencies unless the client library itself needs them to work. We recommend declaring the `com.google.auth:google-auth-library-oauth2-http` dependency explicitly in your project's pom.xml if you need it.
